eval %sh{kak-lsp --kakoune -vvv -c $HOME/.config/kak/kak-lsp.toml -s $kak_session --log /tmp/kak-lsp.log}  # Not needed if you load it with plug.kak.
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
    set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
	lsp-autohover-enable
}
hook global InsertChar \t %{
    exec -draft h@
}
colorscheme gruvbox-dark
add-highlighter global/ number-lines -relative
set global indentwidth 4
set global tabstop 4
set global scrolloff 20,0
