- id: "timer_office_heatpump_off"
  alias: "Turn off office heatpump on timer"
  description: ""
  triggers:
  - trigger: "time"
    at: "17:00:00"
  conditions:
  - condition: "climate.is_on"
    target:
      entity_id: "climate.mike_s_office_heatpump_mike_s_office_mike_s_office_heater"
    options:
      behavior: "any"
      for: "00:00:00"
  actions:
  - action: "climate.turn_off"
    metadata: {}
    target:
      entity_id: "climate.mike_s_office_heatpump_mike_s_office_mike_s_office_heater"
    data: {}
  mode: "single"
- id: "decrease_downstairs_lamp_brightness"
  alias: "Downstairs lamp - decrease brightness when turning button left"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:e3:14:42:b8:7a"
      device_id: "4a713f5c3c61ea99233c62a0c9928ece"
      unique_id: "a4:c1:38:e3:14:42:b8:7a:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "left"
      args: []
      params: {}
  actions:
  - action: "light.turn_on"
    metadata: {}
    target:
      entity_id: "light.dining_room_lamp"
    data:
      brightness_step_pct: -20
  mode: "single"
- id: "increase_downstairs_lamp_brightness"
  alias: "Downstairs lamp - increase lamp brightness when turning button right"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:e3:14:42:b8:7a"
      device_id: "4a713f5c3c61ea99233c62a0c9928ece"
      unique_id: "a4:c1:38:e3:14:42:b8:7a:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "right"
      args: []
      params: {}
  actions:
  - action: "light.turn_on"
    metadata: {}
    target:
      entity_id: "light.dining_room_lamp"
    data:
      brightness_step_pct: 20
  mode: "single"
- id: "toggle_mike_bedroom_lamp"
  alias: "Mike bedroom lamp - toggle when press buttons"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:ab:c9:62:1d:b1"
      device_id: "2fd11b2eac90c1daa1d41a596dd4a57a"
      unique_id: "a4:c1:38:ab:c9:62:1d:b1:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "toggle"
      args: []
      params: {}
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:7e:82:21:7d:37"
      device_id: "628977d0676426888a7f7c217a0710f9"
      unique_id: "a4:c1:38:7e:82:21:7d:37:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "toggle"
      args: []
      params: {}
  actions:
  - type: "toggle"
    device_id: "9f60192a08622db8c597cea034d075b1"
    entity_id: "d3075c2bb97112a2bd9cdc4bd388ba7a"
    domain: "switch"
  mode: "single"
- id: "toggle_downstairs_lamp"
  alias: "Downstairs lamp - toggle on when double press buttons"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:e3:14:42:b8:7a"
      device_id: "4a713f5c3c61ea99233c62a0c9928ece"
      unique_id: "a4:c1:38:e3:14:42:b8:7a:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "remote_button_double_press"
      args: []
      params: {}
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:7e:82:21:7d:37"
      device_id: "628977d0676426888a7f7c217a0710f9"
      unique_id: "a4:c1:38:7e:82:21:7d:37:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "on"
      args: []
      params: {}
  actions:
  - action: "light.toggle"
    metadata: {}
    target:
      entity_id: "light.dining_room_lamp"
    data: {}
  mode: "single"
- id: "dining_room_lamp_lamp_colour"
  alias: "dining_room_lamp - Set to new colour"
  description: ""
  triggers:
  - trigger: "state"
    entity_id: "input_number.downstairs_light_colour_index"
  conditions:
  - condition: "light.is_on"
    target:
      entity_id: "light.dining_room_lamp"
  variables:
    colour:
    - 255
    - 0
    - 0
    colour_cycle:
    - - 255
      - 137
      - 14
    - - 255
      - 193
      - 142
    - - 255
      - 229
      - 207
    - - 255
      - 255
      - 251
    - - 255
      - 112
      - 86
    - - 112
      - 255
      - 86
    - - 129
      - 173
      - 255
    - - 215
      - 151
      - 255
    - - 255
      - 159
      - 242
  actions:
  - action: "light.turn_on"
    metadata: {}
    target:
      entity_id: "light.dining_room_lamp"
    data:
      rgb_color: "{% set idx = states('input_number.downstairs_light_colour_index')\
        \ | int + 1 %} {% set idx = idx % colour_cycle | length %} {% set colour =\
        \ colour_cycle[idx] %} [{{colour[0]-}}, {{colour[1]-}}, {{colour[2]-}}]\n"
  mode: "single"
- id: "cycle_light_colours"
  alias: "Cycle light colours"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:e3:14:42:b8:7a"
      device_id: "4a713f5c3c61ea99233c62a0c9928ece"
      unique_id: "a4:c1:38:e3:14:42:b8:7a:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "remote_button_long_press"
      args: []
      params: {}
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:7e:82:21:7d:37"
      device_id: "628977d0676426888a7f7c217a0710f9"
      unique_id: "a4:c1:38:7e:82:21:7d:37:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "off"
      args: []
      params: {}
  variables:
    colour_cycle:
    - - 255
      - 137
      - 14
    - - 255
      - 193
      - 142
    - - 255
      - 229
      - 207
    - - 255
      - 255
      - 251
    - - 255
      - 112
      - 86
    - - 112
      - 255
      - 86
    - - 129
      - 173
      - 255
    - - 215
      - 151
      - 255
    - - 255
      - 159
      - 242
  actions:
  - action: "input_number.set_value"
    entity_id: "input_number.downstairs_light_colour_index"
    data:
      value: "{% set idx = states('input_number.downstairs_light_colour_index') |\
        \ int + 1 %} {% set idx = idx % colour_cycle | length %} {{ idx }}\n"
  mode: "single"
- id: "heatpump_notify_turn_off"
  alias: "Downstairs heat pump - notify can be turned off at 18 degrees"
  description: ""
  triggers:
  - trigger: "temperature.crossed_threshold"
    target:
      entity_id: "sensor.temperature_humidity_sensor_1_temperature"
    options:
      behavior: "each"
      threshold:
        value:
          active_choice: "number"
          number: 18
          unit_of_measurement: "°C"
        type: "above"
      for:
        hours: 0
        minutes: 10
        seconds: 0
  conditions:
  - condition: "time"
    after: "09:00:00"
    before: "17:00:00"
  actions:
  - action: "notify.send_message"
    metadata: {}
    target:
      device_id: "449719a7d011795e08e37c0f114f4771"
    data:
      message: "Downstairs heat reached threshold "
  mode: "single"
- id: "turn_on_mikes_office_generic_thermostat"
  alias: "Mike's office thermostat - Turn on when clicking office dial"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:a6:32:e2:44:b5"
      device_id: "16447bd2ede6b4941627e3bc14f58c13"
      unique_id: "a4:c1:38:a6:32:e2:44:b5:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "remote_button_short_press"
      args: []
      params: {}
  actions:
  - action: "climate.turn_on"
    metadata: {}
    target:
      entity_id: "climate.mike_s_office_heatpump_mike_s_office_mike_s_office_heater"
    data: {}
  mode: "single"
- id: "turn_off_mikes_office_generic_thermostat"
  alias: "Mike's office thermostat - turn off when double-clicking office dial"
  description: ""
  triggers:
  - trigger: "event"
    event_type: "zha_event"
    event_data:
      device_ieee: "a4:c1:38:a6:32:e2:44:b5"
      device_id: "16447bd2ede6b4941627e3bc14f58c13"
      unique_id: "a4:c1:38:a6:32:e2:44:b5:1:0x0006"
      endpoint_id: 1
      cluster_id: 6
      command: "remote_button_double_press"
      args: []
      params: {}
  actions:
  - action: "climate.turn_off"
    metadata: {}
    target:
      entity_id: "climate.mike_s_office_heatpump_mike_s_office_mike_s_office_heater"
    data: {}
  mode: "single"
- id: "bring_in_washing"
  alias: "Washing machine - Bring in the washing"
  description: ""
  triggers:
  - trigger: "sun"
    event: "sunset"
    offset: 0
  conditions:
  - condition: "switch.is_on"
    target:
      entity_id: "input_boolean.washing_machine_ran_today"
    options:
      behavior: "any"
      for:
        hours: 0
        minutes: 10
        seconds: 0
  actions:
  - action: "input_boolean.turn_off"
    target:
      entity_id: "input_boolean.washing_machine_ran_today"
  - action: "notify.send_message"
    metadata: {}
    target:
      device_id: "449719a7d011795e08e37c0f114f4771"
    data:
      message: "Bring in the washing"
  mode: "single"
- id: "hang_up_washing"
  alias: "Washing machine - Hang up the washing"
  description: ""
  triggers:
  - trigger: "numeric_state"
    entity_id: "sensor.tz3210_cehuw1lw_ts011f_current"
    for:
      hours: 0
      minutes: 20
      seconds: 0
    below: 0.1
  conditions:
  - condition: "switch.is_on"
    target:
      entity_id: "input_boolean.washing_machine_ran_today"
    options:
      behavior: "any"
      for:
        hours: 0
        minutes: 10
        seconds: 0
  actions:
  - action: "notify.send_message"
    metadata: {}
    target:
      device_id: "449719a7d011795e08e37c0f114f4771"
    data:
      message: "The washing machine has finished. Hang up the washing."
  mode: "single"
- id: "washing_machine_ran"
  alias: "Washing machine - Set ran today"
  description: ""
  triggers:
  - trigger: "numeric_state"
    entity_id: "sensor.tz3210_cehuw1lw_ts011f_current"
    for:
      hours: 0
      minutes: 20
      seconds: 0
    above: 0.1
  actions:
  - action: "input_boolean.turn_on"
    target:
      entity_id: "input_boolean.washing_machine_ran_today"
  mode: "single"
