export CPPFLAGS="-I$JAVA_HOME/include"

typeset -U PATH path
path=(
  "$HOME/.local/bin"
  "$HOME/.docker/bin"
  "$HOME/.cargo/bin"
  "$HOME/.config/emacs/bin"
  "$HOME/.orbit/bin"
  "$path[@]"
)
export PATH

. "$HOME/.cargo/env"
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
