typeset -U PATH path
path=("$HOME/.local/bin" "$HOME/.local/share/gem/ruby/3.0.0/bin:" "$HOME/.emacs.d/bin" "$HOME/.cargo/bin" "/opt/homebrew/opt/openjdk@11/bin" "$path[@]")
export PATH

typeset -U CPPFLAGS cppflags
cppflags=("-I/opt/homebrew/opt/openjdk@11/include" "$cppflags[@]")
export CPPFLAGS
