# Uncomment this zmodload and the `zprof` at the bottom of the file
# to profile the startup time
# zmodload zsh/zprof  

if [[ -f "/opt/homebrew/opt/zplug/init.zsh" ]]; then
  export ZPLUG_HOME=/opt/homebrew/opt/zplug
elif [[ -f "$HOME/.zplug/init.zsh" ]]; then
  export ZPLUG_HOME=$HOME/.zplug
fi

if [[ "$ZPLUG_HOME" != "" ]]; then
  source $ZPLUG_HOME/init.zsh
  zplug "mafredri/zsh-async", from:"github", use:"async.zsh"

  zplug "plugins/mise", from:oh-my-zsh
  zplug "plugins/bgnotify", from:oh-my-zsh
  zplug "plugins/colored-man-pages", from:oh-my-zsh
  zplug "plugins/command-not-found", from:oh-my-zsh
  zplug "plugins/python", from:oh-my-zsh
  zplug "plugins/git-auto-fetch", from:oh-my-zsh
  zplug "plugins/gitfast", from:oh-my-zsh
  zplug "plugins/docker", from:oh-my-zsh
  zplug "plugins/tmux", from:oh-my-zsh
  zplug "plugins/aws", from:oh-my-zsh
  zplug "plugins/vi-mode", from:oh-my-zsh
  zplug "plugins/kubectl", from:oh-my-zsh
  zplug "lib/key-bindings.zsh", from:oh-my-zsh
  zplug "dotfiles/config/zsh/acse-kratos", from:local, defer:2
  zplug "dotfiles/config/zsh/miek-aliases-etc", from:local, defer:2
  if [[ $EUID != 0 ]]; then
    ## Skip zoxide for root user to avoid corrupting DB
    zplug "plugins/zoxide", from:oh-my-zsh
  fi
  zplug "romkatv/powerlevel10k", as:theme, depth:1
  zplug "davidde/git"
  zplug "djui/alias-tips"
  zplug "zsh-users/zsh-autosuggestions"
  zplug "zdharma-continuum/fast-syntax-highlighting"
  # Install plugins if there are plugins that have not been installed
  if ! zplug check --verbose; then
      printf "Install? [y/N]: "
      if read -q; then
          echo; zplug install
      fi
  fi
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ $EUID == 0 ]]; then
    # root user needs to set this as disabled or we get warnings
    # (assuming that root is configured to use the same directory as home)
    export ZSH_DISABLE_COMPFIX="true"
fi

HISTCONTROL="ignorespace"

# .zshenv is where I setup custom paths
[[ ! -f ~!/.zshenv ]] || source ~/.zshenv

# Uncomment the following line to have your zsh autostart/join a tmux session
# export ZSH_TMUX_AUTOSTART=true


if [[ "ZPLUG_HOME" != "" ]]; then
  zplug load
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/mwalsh2/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions

# uncomment this (and the first line of the file) to profile the startup
# zprof
