# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
if [[ $EUID == 0 ]]; then
    export ZSH_DISABLE_COMPFIX="true"
fi
HISTCONTROL="ignorespace"
export ZSH="$HOME/.oh-my-zsh"
export NVM_COMPLETION="true"

VSCODE=code
export PATH=$PATH:$HOME/.pulumi/bin:/snap/bin
export PATH=$PATH:$HOME/.cargo/bin:$HOME/.local/bin
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
if [[ $EUID == 0 ]]; then
    # Plugins for root user (same as main but no zoxide)
     plugins=(
      git
      bgnotify
      colored-man-pages
      command-not-found
      thefuck
      python
      git-auto-fetch
      gitfast
      docker
      tmux
      fast-syntax-highlighting
      zsh-autosuggestions
      alias-tips
      aws
      vi-mode
      kubectl
      miek-aliases-etc
    )
else
    # Plugins for regular user
    plugins=(
      git
      zoxide
      bgnotify
      colored-man-pages
      command-not-found
      thefuck
      python
      git-auto-fetch
      gitfast
      docker
      zsh-nvm
      tmux
      fast-syntax-highlighting
      zsh-autosuggestions
      alias-tips
      aws
      vi-mode
      kubectl
      miek-aliases-etc
    )
fi
# Uncomment the following line to have your zsh autostart/join a tmux session
# export ZSH_TMUX_AUTOSTART=true
source $ZSH/oh-my-zsh.sh

# Compilation flags
export ARCHFLAGS="-arch x86_64"
export KUBECONFIG=$(atlas kitt create-context --pid=$$)

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias luamake=/home/mfw56/.local/share/lua-language-server/3rd/luamake/luamake

[[ ! -f ~/.zsh_profile ]] || source ~/.zsh_profile
