# Uncomment this zmodload and the `zprof` at the bottom of the file
# to profile the startup time
# zmodload zsh/zprof  

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ $EUID == 0 ]]; then
    # root user needs to set this as disabled or we get warnings
    # (assuming that root is configured to use the same directory as home)
    export ZSH_DISABLE_COMPFIX="true"
fi

HISTCONTROL="ignorespace"
export ZSH="$HOME/.oh-my-zsh"

# .zshenv is where I setup custom paths
[[ ! -f ~!/.zshenv ]] || source ~/.zshenv
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
if [[ $EUID == 0 ]]; then
    # Plugins for root user (same as main but no zoxide so as to 
    # stop the db getting permissions corrupted)
     plugins=(
      mise
      git
      bgnotify
      colored-man-pages
      command-not-found
      python
      git-auto-fetch
      gitfast
      docker
      tmux
      fast-syntax-highlighting
      zsh-autosuggestions
      alias-tips
      aws
      vi-mode
      kubectl
      miek-aliases-etc
    )
else
    # Plugins for regular user
    plugins=(
      mise
      git
      zoxide
      bgnotify
      colored-man-pages
      command-not-found
      python
      macos
      git-auto-fetch
      gitfast
      docker
      tmux
      fast-syntax-highlighting
      zsh-autosuggestions
      alias-tips
      aws
      vi-mode
      kubectl
      miek-aliases-etc
      acse-kratos
    )
fi

# Uncomment the following line to have your zsh autostart/join a tmux session
# export ZSH_TMUX_AUTOSTART=true


source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# uncomment this (and the first line of the file) to profile the startup
# zprof
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/mwalsh2/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
