return {
  { "folke/tokyonight.nvim" },
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "EdenEast/nightfox.nvim" },
  { "ellisonleao/gruvbox.nvim" },
  { "rose-pine/neovim" },
  { "rockerBOO/boo-colorscheme-nvim" },
  { "shaunsingh/moonlight.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "rktjmp/lush.nvim" },
  { "Scysta/pink-panic.nvim" },
  { "maxmx03/fluoromachine.nvim" },
  { "luisiacc/gruvbox-baby", branch = "main" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "LazyVim/LazyVim", opts = { colorscheme = "catppuccin-mocha" } },
}
